server:
  port: 8888
  servlet:
    context-path: /fan-web

spring:
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://124.222.118.90:3306/fan_web?connectTimeout=5000&socketTimeout=10000&autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: Fan223
      # 关闭空闲检测
      # test-while-idle: false
      # 设置空闲检测语句
      validation-query: SELECT 1

logging:
  level:
    # 指定整个项目的日志级别
    root: info
    # 对某个包指定单独的日志级别
    # fan.config: warn
  # 日志文件, 默认路径为项目根目录下
  file:
    name: all.log
